--
-- PostgreSQL database dump
--

\restrict IK92rfE0kT9U39TS8QlRTXqHcyWuWhr5JzOfFgtfm70VI5X1X8L56epzWjSdlLS

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_conversation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_conversation (
    id bigint NOT NULL,
    is_group boolean NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100),
    bio text NOT NULL,
    owner_id integer
);


ALTER TABLE public.api_conversation OWNER TO postgres;

--
-- Name: api_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_conversation_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_conversation_members (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.api_conversation_members OWNER TO postgres;

--
-- Name: api_conversation_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_conversation_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_conversation_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_message (
    id bigint NOT NULL,
    message_content text NOT NULL,
    date timestamp with time zone NOT NULL,
    conversation_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.api_message OWNER TO postgres;

--
-- Name: api_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_userprofile (
    id bigint NOT NULL,
    image character varying(100),
    bio text,
    user_id integer NOT NULL
);


ALTER TABLE public.api_userprofile OWNER TO postgres;

--
-- Name: api_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: api_conversation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_conversation (id, is_group, name, image, bio, owner_id) FROM stdin;
1	f				4
2	f				6
3	f				7
4	f				4
7	t	Study Room	conversations/photo-1495446815901-a7297e633e8d.jpg		8
6	t	Project Team	conversations/photo-1516321318423-f06f85e504b3.jpg		5
5	t	Django Developers	conversations/photo-1529156069898-49953e39b3ac.jpg		4
\.


--
-- Data for Name: api_conversation_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_conversation_members (id, conversation_id, user_id) FROM stdin;
1	1	4
2	1	5
3	2	10
4	2	6
5	3	9
6	3	7
7	4	11
8	4	4
9	5	4
10	5	6
11	5	8
12	5	10
13	5	11
14	6	9
15	6	4
16	6	5
17	6	7
18	7	6
19	7	8
20	7	9
21	7	10
22	7	11
\.


--
-- Data for Name: api_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_message (id, message_content, date, conversation_id, user_id) FROM stdin;
1	Hey Sarah, did you finish the new dashboard?	2026-09-12 22:10:21.959639+00	1	4
2	Almost. I'm fixing the responsive layout right now.	2026-09-12 22:10:21.962269+00	1	5
3	Nice. Are you using CSS grid for it?	2026-09-12 22:10:21.96361+00	1	4
4	Yeah, grid for the main layout and flex for the smaller components.	2026-09-12 22:10:21.965019+00	1	5
5	That should work well on mobile too.	2026-09-12 22:10:21.966433+00	1	4
6	Exactly. I'll push the changes tonight.	2026-09-12 22:10:21.967929+00	1	5
7	Hey James, I finally finished the authentication API.	2026-09-12 22:10:21.970171+00	2	6
8	Nice! Are you using JWT?	2026-09-12 22:10:21.971132+00	2	10
9	Yeah, access and refresh tokens.	2026-09-12 22:10:21.971959+00	2	6
10	Good choice. Where are you storing the refresh token?	2026-09-12 22:10:21.972737+00	2	10
11	HttpOnly cookies.	2026-09-12 22:10:21.973356+00	2	6
12	That's what I'd use too. Much safer than localStorage for that use case.	2026-09-12 22:10:21.973922+00	2	10
13	What do you think about the new profile page?	2026-09-12 22:10:21.975414+00	3	7
14	I like it. The layout feels much cleaner.	2026-09-12 22:10:21.976126+00	3	9
15	I'm still not sure about the spacing between the sections.	2026-09-12 22:10:21.976797+00	3	7
16	Maybe give the profile header a little more breathing room.	2026-09-12 22:10:21.977348+00	3	9
17	Good idea. I'll try that.	2026-09-12 22:10:21.977937+00	3	7
18	Hey Sophia, how is the notification system going?	2026-09-12 22:10:21.979628+00	4	4
19	Pretty good. I'm using WebSockets for the real-time part.	2026-09-12 22:10:21.980797+00	4	11
20	Are you using Django Channels?	2026-09-12 22:10:21.98142+00	4	4
21	Yeah, with Redis as the channel layer.	2026-09-12 22:10:21.98198+00	4	11
22	Nice. That should work really well.	2026-09-12 22:10:21.982855+00	4	4
23	What is everyone working on this week?	2026-09-12 22:10:21.985929+00	5	4
24	I'm working on a Django REST API for a small project.	2026-09-12 22:10:21.98658+00	5	6
25	I'm working on PostgreSQL optimization.	2026-09-12 22:10:21.98713+00	5	10
26	I'm trying to understand Django signals better.	2026-09-12 22:10:21.987653+00	5	8
27	I'm working on a real-time notification system with WebSockets.	2026-09-12 22:10:21.988257+00	5	11
28	Nice. Are you using Django Channels?	2026-09-12 22:10:21.98883+00	5	4
29	Yeah, Channels with Redis.	2026-09-12 22:10:21.989335+00	5	11
30	I've been wanting to learn Channels. Is it difficult?	2026-09-12 22:10:21.989808+00	5	6
31	The basic setup isn't too bad. The tricky part is understanding the async side.	2026-09-12 22:10:21.990284+00	5	11
32	That's exactly the part I'm struggling with.	2026-09-12 22:10:21.990822+00	5	8
33	Redis makes a lot more sense once you understand what the channel layer is doing.	2026-09-12 22:10:21.991329+00	5	10
34	We should probably make a small project together sometime.	2026-09-12 22:10:21.991911+00	5	4
35	I've pushed the latest frontend changes.	2026-09-12 22:10:21.994146+00	6	5
36	I checked the new design. Looks much better.	2026-09-12 22:10:21.994707+00	6	7
37	The profile page looks great.	2026-09-12 22:10:21.995623+00	6	9
38	I'll connect the new UI to the API tonight.	2026-09-12 22:10:21.996791+00	6	4
39	Perfect.	2026-09-12 22:10:21.997489+00	6	5
40	Can we also add loading states?	2026-09-12 22:10:21.998078+00	6	7
41	Yeah, I'll handle those.	2026-09-12 22:10:21.998738+00	6	4
42	And maybe an empty-state message when there are no conversations.	2026-09-12 22:10:21.999556+00	6	9
43	Good idea. I'll add that tomorrow.	2026-09-12 22:10:22.000164+00	6	5
44	Anyone studying Django today?	2026-09-12 22:10:22.00254+00	7	8
45	Yep 😂	2026-09-12 22:10:22.003241+00	7	6
46	I'm going through DRF permissions.	2026-09-12 22:10:22.003961+00	7	10
47	I'm learning Docker at the moment.	2026-09-12 22:10:22.004549+00	7	9
48	I'm trying to understand WebSockets better.	2026-09-12 22:10:22.005078+00	7	11
49	We should share useful resources here.	2026-09-12 22:10:22.005628+00	7	8
50	Agreed. I'll post some DRF notes later.	2026-09-12 22:10:22.00615+00	7	6
51	And I'll share some PostgreSQL stuff.	2026-09-12 22:10:22.006656+00	7	10
52	Perfect.	2026-09-12 22:10:22.007152+00	7	9
\.


--
-- Data for Name: api_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_userprofile (id, image, bio, user_id) FROM stdin;
30	users/Elegant_Summer_Mens_Fashion.jpg	i am super user	1
31	users/download_3_EjRUME3.jpg		12
3	users/12947917676104974_mskgtK5.jpg	Full-stack developer interested in Django and React.	4
4	users/Linkedin_photo_retka4c.jpg	Frontend developer · Next.js · TypeScript.	5
5	users/Harboriis_harboriis_on_X.jpg	Backend developer learning Django REST Framework.	6
6	users/Toronto_Headshot_Photography_for_Lawyers.jpg	UI/UX designer who loves clean interfaces.	7
7	users/Elegant_Summer_Mens_Fashion_0S3jYun.jpg	Computer science student and open-source enthusiast.	8
8	users/Linkedin_photo.jpg	Junior developer exploring cloud technologies.	9
9	users/12947917676104974.jpg	Python developer · APIs · PostgreSQL.	10
10	users/34762228370192958.jpg	Software engineer interested in real-time applications.	11
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add user profile	3	add_userprofile
2	Can change user profile	3	change_userprofile
3	Can delete user profile	3	delete_userprofile
4	Can view user profile	3	view_userprofile
5	Can add conversation	1	add_conversation
6	Can change conversation	1	change_conversation
7	Can delete conversation	1	delete_conversation
8	Can view conversation	1	view_conversation
9	Can add message	2	add_message
10	Can change message	2	change_message
11	Can delete message	2	delete_message
12	Can view message	2	view_message
13	Can add log entry	4	add_logentry
14	Can change log entry	4	change_logentry
15	Can delete log entry	4	delete_logentry
16	Can view log entry	4	view_logentry
17	Can add permission	6	add_permission
18	Can change permission	6	change_permission
19	Can delete permission	6	delete_permission
20	Can view permission	6	view_permission
21	Can add group	5	add_group
22	Can change group	5	change_group
23	Can delete group	5	delete_group
24	Can view group	5	view_group
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add content type	8	add_contenttype
30	Can change content type	8	change_contenttype
31	Can delete content type	8	delete_contenttype
32	Can view content type	8	view_contenttype
33	Can add session	9	add_session
34	Can change session	9	change_session
35	Can delete session	9	delete_session
36	Can view session	9	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
4	pbkdf2_sha256$1200000$8dA08xziBCnSmaqeEUvyW8$OEg/08r9ZKc0dXeUQhw/jWqCfgGdUyLfHGyZwrPvgww=	\N	f	alex				f	t	2026-09-12 22:10:19.557358+00
5	pbkdf2_sha256$1200000$6l6cWikeFtXQ9jeWvaKTAW$ctmRbszuiYWxJdeRd8vChmSwApRbsXfK8mt78BOFAy0=	\N	f	sarah				f	t	2026-09-12 22:10:19.868466+00
6	pbkdf2_sha256$1200000$4lorOjg893r4aV9Zzjnb7y$aXPF6Ol9Z/Qvm9n4CPOTV0ePI3tH1pv3SYvfyoX9WcY=	\N	f	daniel				f	t	2026-09-12 22:10:20.168108+00
7	pbkdf2_sha256$1200000$AEQPcBsEljLwvvl1eWtejs$df5r1sMN3tpVEBFdSETZgY13UAusWaTExRxTpPJjdJE=	\N	f	emma				f	t	2026-09-12 22:10:20.461188+00
8	pbkdf2_sha256$1200000$X2Ilb22v8H05ZLMb7yAy54$zPuKYKlhupRBf1iUi1+5DGNc7QEnvlpLCi9ZSIulPNE=	\N	f	mike				f	t	2026-09-12 22:10:20.767257+00
9	pbkdf2_sha256$1200000$RzCKtypMfz1sTLozJAOolC$/1xHwd5OM3pZEldWEBghK5DS4/BZLjANsVEZN4qxjck=	\N	f	olivia				f	t	2026-09-12 22:10:21.037012+00
10	pbkdf2_sha256$1200000$tzrdkELvMufZGTH0vHuNPK$gObw1fhMozqXrkt2U/QjUxHwCtHYCgo/OxW5LMGduuY=	\N	f	james				f	t	2026-09-12 22:10:21.318404+00
11	pbkdf2_sha256$1200000$VtH9m6UpMej9aCYNBkmZOr$XJLlVSe6cPHxjRWN8uI+fsFaidbq7v3xTT9+mjTO7o8=	\N	f	sophia				f	t	2026-09-12 22:10:21.591533+00
1	pbkdf2_sha256$1200000$0wAeX2fBpjvWOloB2PQWI4$FBABTPKwHlzaPfP9iT8jls8m4Yp5TVhZkIRSpwX1bHk=	2026-09-12 21:56:15.020233+00	t	superuser			superuser@gmail.com	t	t	2026-09-12 21:55:59.580536+00
12	pbkdf2_sha256$1200000$pcaZYlkLMVKZ3GsLOxvzqo$RDGBpdeN462mDW5/rZ8jxRK+IqimIS4/Sij44gf1hS4=	\N	f	mhrb			ghasemimehrab9@gmail.com	f	t	2026-09-12 22:32:46.535805+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-12 22:23:34.922275+00	26	superuser	3		3	1
2	2026-09-12 22:25:40.517394+00	27	superuser	3		3	1
3	2026-09-12 22:27:03.838168+00	10	sophia	2	[{"changed": {"fields": ["Image"]}}]	3	1
4	2026-09-12 22:27:14.715424+00	9	james	2	[{"changed": {"fields": ["Image"]}}]	3	1
5	2026-09-12 22:27:25.591609+00	8	olivia	2	[{"changed": {"fields": ["Image"]}}]	3	1
6	2026-09-12 22:27:36.237239+00	7	mike	2	[{"changed": {"fields": ["Image"]}}]	3	1
7	2026-09-12 22:27:46.67047+00	6	emma	2	[{"changed": {"fields": ["Image"]}}]	3	1
8	2026-09-12 22:27:51.30529+00	5	daniel	2	[]	3	1
9	2026-09-12 22:28:02.539886+00	5	daniel	2	[{"changed": {"fields": ["Image"]}}]	3	1
10	2026-09-12 22:28:20.375891+00	4	sarah	2	[{"changed": {"fields": ["Image"]}}]	3	1
11	2026-09-12 22:28:28.924841+00	3	alex	2	[{"changed": {"fields": ["Image"]}}]	3	1
12	2026-09-12 22:29:04.193041+00	7	Study Room	2	[{"changed": {"fields": ["Image"]}}]	1	1
13	2026-09-12 22:29:48.497962+00	6	Project Team	2	[{"changed": {"fields": ["Image"]}}]	1	1
14	2026-09-12 22:29:59.712055+00	5	Django Developers	2	[{"changed": {"fields": ["Image"]}}]	1	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	api	conversation
2	api	message
3	api	userprofile
4	admin	logentry
5	auth	group
6	auth	permission
7	auth	user
8	contenttypes	contenttype
9	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-11 20:02:26.81071+00
2	auth	0001_initial	2026-09-11 20:02:26.874211+00
3	admin	0001_initial	2026-09-11 20:02:26.895485+00
4	admin	0002_logentry_remove_auto_add	2026-09-11 20:02:26.905656+00
5	admin	0003_logentry_add_action_flag_choices	2026-09-11 20:02:26.918079+00
6	api	0001_initial	2026-09-11 20:02:27.006969+00
7	api	0002_remove_userprofile_groups_remove_groupmessage_group_and_more	2026-09-11 20:02:27.177249+00
8	api	0003_conversation_owner	2026-09-11 20:02:27.203761+00
9	api	0004_alter_conversation_owner	2026-09-11 20:02:27.23016+00
10	api	0005_alter_conversation_owner	2026-09-11 20:02:27.258573+00
11	contenttypes	0002_remove_content_type_name	2026-09-11 20:02:27.291754+00
12	auth	0002_alter_permission_name_max_length	2026-09-11 20:02:27.313861+00
13	auth	0003_alter_user_email_max_length	2026-09-11 20:02:27.334365+00
14	auth	0004_alter_user_username_opts	2026-09-11 20:02:27.362161+00
15	auth	0005_alter_user_last_login_null	2026-09-11 20:02:27.375216+00
16	auth	0006_require_contenttypes_0002	2026-09-11 20:02:27.377721+00
17	auth	0007_alter_validators_add_error_messages	2026-09-11 20:02:27.390663+00
18	auth	0008_alter_user_username_max_length	2026-09-11 20:02:27.405759+00
19	auth	0009_alter_user_last_name_max_length	2026-09-11 20:02:27.419532+00
20	auth	0010_alter_group_name_max_length	2026-09-11 20:02:27.436505+00
21	auth	0011_update_proxy_permissions	2026-09-11 20:02:27.45341+00
22	auth	0012_alter_user_first_name_max_length	2026-09-11 20:02:27.470923+00
23	sessions	0001_initial	2026-09-11 20:02:27.48291+00
24	api	0006_alter_userprofile_bio	2026-09-12 22:22:32.871796+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
z3dk8vd75qkva04qlqkx3j9xh7yre9xn	.eJxVjMsOgjAURP-la9PYcm8Rl-75BnIfraCmTSisjP8uJCx0OXPOzNsMtC7jsNY4D5Oaq3Hm9NsxyTPmHeiD8r1YKXmZJ7a7Yg9abV80vm6H-3cwUh23deMgclIfO0RshDmgdK0j9HhRUADqzsIStKGEznsBSiGAQGq31Ebz-QLrdjf6:1x5Vhn:HErZz5P-nyNoRNXPgQDy7rMQKQMEECRea-SzmC1OjEE	2026-09-26 21:56:15.026632+00
\.


--
-- Name: api_conversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_conversation_id_seq', 7, true);


--
-- Name: api_conversation_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_conversation_members_id_seq', 22, true);


--
-- Name: api_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_message_id_seq', 52, true);


--
-- Name: api_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_userprofile_id_seq', 31, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 12, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 14, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: api_conversation_members api_conversation_members_conversation_id_user_id_b9c7b14f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation_members
    ADD CONSTRAINT api_conversation_members_conversation_id_user_id_b9c7b14f_uniq UNIQUE (conversation_id, user_id);


--
-- Name: api_conversation_members api_conversation_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation_members
    ADD CONSTRAINT api_conversation_members_pkey PRIMARY KEY (id);


--
-- Name: api_conversation api_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation
    ADD CONSTRAINT api_conversation_pkey PRIMARY KEY (id);


--
-- Name: api_message api_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_message
    ADD CONSTRAINT api_message_pkey PRIMARY KEY (id);


--
-- Name: api_userprofile api_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_pkey PRIMARY KEY (id);


--
-- Name: api_userprofile api_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_conversation_members_conversation_id_af0d9e41; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_conversation_members_conversation_id_af0d9e41 ON public.api_conversation_members USING btree (conversation_id);


--
-- Name: api_conversation_members_user_id_4bfb8a8c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_conversation_members_user_id_4bfb8a8c ON public.api_conversation_members USING btree (user_id);


--
-- Name: api_conversation_owner_id_6b7a2602; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_conversation_owner_id_6b7a2602 ON public.api_conversation USING btree (owner_id);


--
-- Name: api_message_conversation_id_e0f0e1a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_message_conversation_id_e0f0e1a5 ON public.api_message USING btree (conversation_id);


--
-- Name: api_message_user_id_7f9577a9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_message_user_id_7f9577a9 ON public.api_message USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_conversation_members api_conversation_mem_conversation_id_af0d9e41_fk_api_conve; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation_members
    ADD CONSTRAINT api_conversation_mem_conversation_id_af0d9e41_fk_api_conve FOREIGN KEY (conversation_id) REFERENCES public.api_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_conversation_members api_conversation_members_user_id_4bfb8a8c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation_members
    ADD CONSTRAINT api_conversation_members_user_id_4bfb8a8c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_conversation api_conversation_owner_id_6b7a2602_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_conversation
    ADD CONSTRAINT api_conversation_owner_id_6b7a2602_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_message api_message_conversation_id_e0f0e1a5_fk_api_conversation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_message
    ADD CONSTRAINT api_message_conversation_id_e0f0e1a5_fk_api_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.api_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_message api_message_user_id_7f9577a9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_message
    ADD CONSTRAINT api_message_user_id_7f9577a9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_userprofile api_userprofile_user_id_5a1c1c92_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_user_id_5a1c1c92_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict IK92rfE0kT9U39TS8QlRTXqHcyWuWhr5JzOfFgtfm70VI5X1X8L56epzWjSdlLS

